version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 661388510615.dkr.ecr.us-east-1.amazonaws.com
      - REPO=661388510615.dkr.ecr.us-east-1.amazonaws.com/culi-prod/backend
      - TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
  build:
    commands:
      - echo Building Docker image with tag $TAG...
      - docker build -t $REPO:$TAG .
      - docker tag $REPO:$TAG $REPO:latest
  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $REPO:$TAG
      - docker push $REPO:latest
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
